<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3mgC1eg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3mgC1eg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3mgC1eg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3mgC1eg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3mgC1eg\App_KernelDevDebugContainer([
    'container.build_hash' => '3mgC1eg',
    'container.build_id' => '05a82ca3',
    'container.build_time' => 1649632855,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3mgC1eg');
